# レースデータのcolumns
race_data_columns = [
    'race_id',
    'race_round',
    'race_grade',
    'race_course',
    'weather',
    'track_condition',
    'time',
    'date',
    'location',
    'race_class',
    'total_horse_number',
    'frame_number_first',
    'horse_number_first',
    'frame_number_second',
    'horse_number_second',
    'frame_number_third',
    'horse_number_third',
    'win',
    'show_1',
    'show_2',
    'show_3',
    'bracket_quinella',
    'quinella',
    'quinella_place_1_2',
    'quinella_place_1_3',
    'quinella_place_2_3',
    'exacta',
    'trio',
    'trifecta',
    'ground_index',
    'lap_time',
    'pace_time'
]

# 競走馬データのcolumns
horse_data_columns = [
    'race_id',
    'rank',
    'frame_number',
    'horse_number',
    'horse_id',
    'sex_and_age',
    'burden_weight',
    'rider_id',
    'goal_time',
    'margin',
    'speed_index',
    'rank_path',
    'last3f_time',
    'win_odds',
    'popular',
    'horse_weight',
    'remark',
    'affiliation',
    'tamer_id',
    'owner_id'
]


# 競走馬の調教データのcolumns
training_data_columns = [
    'horse_id',
    'race_id',
    'course_type',
    'course_condition',
    'lap_time_1',
    'lap_time_2',
    'lap_time_3',
    'lap_time_4',
    'lap_time_5',
    'top_lap_time_1',
    'top_lap_time_2',
    'top_lap_time_3',
    'top_lap_time_4',
    'top_lap_time_5',
    'position',
    'running_style',
    'evaluation_grade',
]